---
- name: Fix Node Networking
  hosts: all
  become: true
  tasks:
    - name: Disable nm-cloud-setup service
      systemd:
        name: nm-cloud-setup.service
        enabled: no
        state: stopped
      ignore_errors: true

    - name: Disable nm-cloud-setup timer
      systemd:
        name: nm-cloud-setup.timer
        enabled: no
        state: stopped
      ignore_errors: true

    - name: Disable ufw
      systemd:
        name: ufw
        enabled: no
        state: stopped
      ignore_errors: true

    - name: Disable firewalld
      systemd:
        name: firewalld
        enabled: no
        state: stopped
      ignore_errors: true

    - name: Remove search domain from resolv.conf
      lineinfile:
        path: /etc/resolv.conf
        state: absent
        regexp: '^search.*treympick\.me'

    - name: Flush NAT table
      command: iptables -t nat -F

    - name: Restart K3s (Server)
      systemd:
        name: k3s
        state: restarted
      when: "'server' in group_names"
      ignore_errors: true

    - name: Restart K3s Agent
      systemd:
        name: k3s-agent
        state: restarted
      when: "'agent' in group_names"
      ignore_errors: true
