apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: headlamp-https-redirect
  namespace: kube-system
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
