apiVersion: v1
kind: Secret
metadata:
    name: headlamp-oidc-values
    namespace: kube-system
stringData:
    values.yaml: ENC[AES256_GCM,data:8GOJCkhcBo0uHTWd09QvyNthcRM05zswm9mV59Uy1YbNYz0fL3o0GB66M7PgnH+Ex8FUqngD0H70LbEIJVbv9NAJSq0Vzhhy7w943ULS0gqu9rBA6e9UaraPqGOn1rmJi5l2yAE8/iv7j5+58g5WmQj69w2OoxAzqdFBI+F2xrovgJDNlF1PnFU8AUo7jQYW2cjzrr+JXYsECfp/Yc+ujmHowmFgq8Qzp+CdQl3/YFsopRDnz5mBhXqMe9H7WTgZek0zox/tYcEwZFGy6L8LBjvl3lEAGuRdUBuPiRe8FtLDaGVR4Ol5OYSVc+tqZ35KbJnFpqd7pK5bZGbpDzpQEg==,iv:ROPsP9b4a7Wg4HLfD7k37hTfZpRBXTVhlQwJixR8FuY=,tag:eaLI2FQO0inQFhNmIWhqJg==,type:str]
sops:
    age:
        - recipient: age1p0vkumkk7q8ru6skfdqttdjeradz78s7fua8mvv54apt935yzsyqyleqjr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArVG9hUE5nMFJKQ3lpL1lp
            bDk1cjJVdUxFSFFTWVpoK0llVUlqZ0UzYUcwCi9JbmdHYnZRRFZVMjNrS2V5TitD
            cUkxTmp1TFcraXh0a21BV2tOYmN3SjAKLS0tIER3THRBOFY5K3hKK0ZsYk1pNUJY
            S01peVU5YXUxazRINVJPdDhHQUdiNUkKwwDADKiBtlY2J7GdwFcjLcBZTm2282t7
            Dsap+/OcHyg1UBPpoX2AwCYHGjXUrnufg1fycgXrzkpLe41ssmQUxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-12T23:35:58Z"
    mac: ENC[AES256_GCM,data:pW01fotej3LyMxRozU4DuD5+IYpiiN09a+sltn/4L0omTH9L8kRyTs8S0hdnVheswubwD78scsHu/dxhBzgNABS/NZ7bR9zx7pHkN7u/Es1VdtM7jyoSXZO+gZm0QOB4PzYLaDGYTALtEsNmErvIGtVAzS5DjNJLeeBYhVF/hdw=,iv:X/YSeJDLj7ygnwljTHjrmgdAyHBZ9dL2y9DwI9a72Lc=,tag:MHuUHYg+Y8Gk2hgyBdsaDA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
