apiVersion: v1
kind: Secret
metadata:
    name: headlamp-oidc-values
    namespace: kube-system
stringData:
    values.yaml: ENC[AES256_GCM,data:1IgPfIsKRfIxqtFiV+ZH6+qVwIQmMsxhGlOWxiqYMWE+QIulM61+XUq1i4H0iFh6mkVeAnQH6S+9U4RNmO2wKvMpsQjuts3i5QmT1ms70gk9dL+qDr5GuSkIVd2PaLgyPbQtgv8SofNO9/+cL4HS0FLffTjxqGK/Ljmwf2f3AcmspBAVAg+LXL+EzO7fM40kFqI3onKJnDePQns3pkQHBaiV8Z33djTYWiJbj4gXO9K8pttagzMed2vOhH3rU6Y17Nt9NQGeZCSVos88hBrT4eYiElPs3MCejKLkF2jElxIDrDCnDZwA+X6kb1Ucxok6S4FVBUfh6uU1lhjz9Vbk4tVd,iv:Bon5B31N4jkjIMQOaiJ80/CKqCinlx6wLgmq021ghts=,tag:GWS/t09KG3cD7SZ5VzX1ug==,type:str]
sops:
    age:
        - recipient: age1p0vkumkk7q8ru6skfdqttdjeradz78s7fua8mvv54apt935yzsyqyleqjr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1U1pja0wyMWUwa2R0a25T
            TmlaM2dQM0IwOHg1MHJ6NzBYUFYrQkdyZFZJCnZ4Z3lTTFlYZXdpcWdQaUFNbE1M
            TVFnZU1nM2tyeXJ4NEg1YUJjTUpVT3cKLS0tIHJRMWxNeWU1aVkyV1ZIR0ZxOEVx
            aXE1TXpkeGlZZURvUWJxQnMxTmp4QVEKAuhJ6GPwERm0Lq8/UuHhn6bzAdox2La3
            RhfFjhAzXvMRS5YMPdV5fMHDNc4/sSCrUCFGQtoAsv7ZuoydKT4aDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T21:57:21Z"
    mac: ENC[AES256_GCM,data:Z5qd8XhDDti7HC43LuWuC3cEl1ZH+ZdyQsd8AEXsWQ0eTd3kERIh/eKaW680oiUtreUdw8SqIdi1bZJ9jrMnzfEDK2dEN7P+q/DI52ZSea2LK2nrG1ye4T0D7JIBiT5Pvg2XLYYC6GI39LuKgJ8UbDagK7opl6mDxfRw2ljHZow=,iv:bBGwocG6jaXKoBsckIdjSYi7D86MzJZM2CMUOyU35Ts=,tag:Tl+g+ArshYHXt1bojUUT7w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
