apiVersion: v1
kind: Secret
metadata:
    name: vikunja-secret
    namespace: vikunja
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:CDRWCC4mvg==,iv:iRP+3/QSC9sP3po70qGKbtUla6L8yKU+uf8+OgmOFHU=,tag:7zJhzkK/AZ/yH47/ZHiFGw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:7tAXojC5hdCuXp4gg/Um1CIO+jZ8LE7btfVWxdc+Ca0=,iv:8V2B9/zG5vPd9c58E0pxdUbiJNgWrr77aK/0DcYc35w=,tag:uRED//CiKnbbBNumckUGxw==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:9/3OKZy3gw==,iv:A2UvvzGiXwTccsc0lMVSq4OHUixs6uLEF+hotb8CBZc=,tag:RyQU5myqvkKHLuopQQLK4A==,type:str]
    VIKUNJA_DATABASE_HOST: ENC[AES256_GCM,data:uTwlroWYWZnompC7NqGNx1oPtdB11reSmZTfoZlx5i7xlw==,iv:Cg5OqMuXOKRtdTGw6R92PLKdjU4JQWVc+wCYmdP9nH8=,tag:14ud93TSbDH6J30ibe2FZQ==,type:str]
    VIKUNJA_DATABASE_USER: ENC[AES256_GCM,data:HxGu1Ae0aQ==,iv:NoO83SI9qftM2Uh8u5Vl7v5chpcB+km81XD8xlDHWpA=,tag:V50qAoiGcNRJGLII00xAlw==,type:str]
    VIKUNJA_DATABASE_PASSWORD: ENC[AES256_GCM,data:nqTFcbYzWx8FPq3C6NqCnzLoVw15NzfGo5y+5freM1U=,iv:jpuI1DRD4tMs5YdGbo7RImVhvAhKsoyvWF16S7Oyaug=,tag:gxVQQqcNKQM2ly4y4IW5eQ==,type:str]
    VIKUNJA_DATABASE_DATABASE: ENC[AES256_GCM,data:y4o62ymAkw==,iv:1lRdK7WU5dG3hPD9un/hzgk6xauuoznHJJezB8+s2b8=,tag:RTjTnPnGq/k6WpMF+k674Q==,type:str]
    VIKUNJA_SERVICE_JWTSECRET: ENC[AES256_GCM,data:/QMgoDGNdxPPR/o+995EFOUO5jIVHiONWZivaj1fvLig1OZ7QTGGpXB4x3Y=,iv:xfAc50NFBGqZATVIZBvZOBUj2kNhVxUSGdPVGUFxd3E=,tag:1qqvS1YfAnDZIvazIZDDRg==,type:str]
sops:
    age:
        - recipient: age1p0vkumkk7q8ru6skfdqttdjeradz78s7fua8mvv54apt935yzsyqyleqjr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTXRBbWRKZmxTN2tnQms0
            M21admRUZ1hJVnpRS1NQVmtJTEhCT3E3VHc4CkFuR25ZQXNGL2U5eVY4T0lVZHdS
            M1RTUklBYk1SaGtueWQyN3Rkak5WaUEKLS0tIHE0VUNqTkxsWFIzYUpISW0vZysx
            ZFdOODNXRXJqTXhOWkpoRmNqdlZNZ1EKTEqGFqBzfYByXJz8h6GNP5pZVCi+WiaQ
            HfBD/8VvfJ1CmBC75VgeX3ewPzGPaWp+IMqxCy/nbiXpYXAutMH6/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T13:26:59Z"
    mac: ENC[AES256_GCM,data:N8cOvBIJzLCRy+3tZi+WBySvZFIIro8+rJ1+ladv5onqYGlJ1fVnmooSdQepLMMJ42RU1XsILfHj+honmhhDl61r03HgYmruKayGYGKGighlPOmntl3qZ4ji34qHJqIfrWmLVv0TsT321POveF8a90zrUf5pVdadynAN30jzGQY=,iv:a1HoUcByCnShWav7pAspkmgHGbXLuyzGYxqRigSTlbo=,tag:BzoD27aSk7h1tEeZ/PT3Lg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
