apiVersion: v1
kind: Secret
metadata:
    name: fundfetti-secret
    namespace: fundfetti
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:GnrX4+PDVAU=,iv:Joq6aMbjnDfBg8Eq/KMq68oJQY9ivSHKznt8Ou/9HQ4=,tag:XqgTXbZVlvuO7ilXVGeiaA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:L5pWoCpDtG8HNf45kz5Xc160FJAH3oyE,iv:pxDUyvu3zNHKjv5u2+5LCEH44HEoocGoQNTV+cgQ2ew=,tag:WAM6vtdvPRkLI9W6K7rVKw==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:Y+aP+UpJVmm1,iv:n2b8uyuno3MinN43OlH/hPOnInCF5DV5I5wxKTXN8vc=,tag:hTsg4f9EMlh6J5o8z5rETQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:VZ7FslGu6fDztKX9JYTBMxUXxdziUAru8w9RO/++KZbc6wTPAbkCpVYNhjtgcwXkWSEDocWJJyBQlyULH7YoC9b6JrNliXiFqKek7EcCQ/bzm55G,iv:gjDabKWR/Pw89IjbRNnL6lHaKtzFRb851jgRGJk5a2c=,tag:h6/2sPa+h4JX39NEIzOpRQ==,type:str]
    SESSION_KEY: ENC[AES256_GCM,data:MvGzqQcxjttOr8qCalJ1MRkZN2RIxa8qE0Cwyed9TPQVicpGC4+/HePrAr4=,iv:9hMkwts39gcsocZgEpVELXZUOLB+sCtfOnvGVuO111A=,tag:lqTK7I9F3dBLAF6hFFDCWg==,type:str]
    RESEND_API_KEY: ENC[AES256_GCM,data:PKs/Bd/8m0WEp1RYlPhayYIS8BLi7CxetSIx0zaOpFArJEPW,iv:URR4unL+m3MHCnqLVURn8m6R047KBaY8Q8muimR9w8c=,tag:vTw3jq7qbLcaXvakWH/RAg==,type:str]
    R2_ACCESS_KEY_ID: ENC[AES256_GCM,data:jkhpwLRZ9MdWRIpYFi/r9LoR73JoF9WX3iVUljcCFE4=,iv:ma1pulbXT9sMmQFK0gwrjD2mbAF76uNjS6ViBbhS1l4=,tag:bFPmgc9niT9mFLlLgsqdFg==,type:str]
    R2_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:3d680AhuQEE4dRZzel3Hkdsb0eRaK36RJtYgzO6TlOF97HRJOVGFCyNvrCesTRH9FFm4Imn8dlUQc7unydbn+Q==,iv:AvYbxloW5rzkNNjuVNuhMYT20ycsx+9I3bCEp5AdNqQ=,tag:nV6awmWZI8wr+VeyQ9XjIw==,type:str]
    R2_BUCKET_NAME: ENC[AES256_GCM,data:d/503s9J22wofwruVa1f72g=,iv:QzFjBFMbDOBbdoxZQE5cOqO4QaKzJQn29MUPdp9Myco=,tag:s8X2yhRww1CbBTNNVDpzOw==,type:str]
    R2_ENDPOINT_URL: ENC[AES256_GCM,data:aINKJgPjp/OwbBiEZdPs8EoYyeY6wtXi6KXgT4QBDrLjfQacNRy46+wtXJxuapjmNMTZvMZ92wU1Y/oI2HMRVjk=,iv:1DwUOzX96oxyFAi9BnOrC0HqtFhEGO4cw4YDcT8iWwI=,tag:XKj8pIIqB6ph/Vi5AYIPtg==,type:str]
sops:
    age:
        - recipient: age1p0vkumkk7q8ru6skfdqttdjeradz78s7fua8mvv54apt935yzsyqyleqjr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUmhGZVYxcE9XYVFXMWtt
            ejdlb2hBSnMxRjVwRldJL0xYaW00WDZjcmxJCllZWmFiUmxWUWJhZVVTcHJEcFVS
            OFlOMS9WMW5IeXVBVFBaQ1drSFJEM1EKLS0tIE96ZDhtTTJ3eWUwR0lqV3Y5cTFQ
            WHdEQmdCYy9ZYWFJOW1oeFo5RkpTcVUKeNF77JPqFMoLBLy8xTyn2SfDY0QHcghm
            0ipZT0IO3wenhSDayADjRojWswpyUi9xxcuar0f+PfD7kLqpMuFzsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-02T01:28:11Z"
    mac: ENC[AES256_GCM,data:4TuKnyzPOlopNHV6shIQxsT1cclvV0Bo3OJU00LSw+yAMfDxbWpDi5u7hhqj6OP4uPh/z0+qzAneMBu8LGMDGAts9uX8MFHMgGR3DyfcEPHJ2mz9BwGG5uV35h+MCdlkezi6mQY+Iagxm6OPAyL5OC/Nne6vEwNxWcT79w57Z9E=,iv:/zQwtQ3Q1D/tDRHVZsduhjvWOeMe46myhETqV/3K7qk=,tag:8O2A6itEwSOGZd56IBLUmw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
