apiVersion: v1
kind: Secret
metadata:
    name: fundfetti-secret
    namespace: fundfetti
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:GnrX4+PDVAU=,iv:Joq6aMbjnDfBg8Eq/KMq68oJQY9ivSHKznt8Ou/9HQ4=,tag:XqgTXbZVlvuO7ilXVGeiaA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:L5pWoCpDtG8HNf45kz5Xc160FJAH3oyE,iv:pxDUyvu3zNHKjv5u2+5LCEH44HEoocGoQNTV+cgQ2ew=,tag:WAM6vtdvPRkLI9W6K7rVKw==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:Y+aP+UpJVmm1,iv:n2b8uyuno3MinN43OlH/hPOnInCF5DV5I5wxKTXN8vc=,tag:hTsg4f9EMlh6J5o8z5rETQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:VZ7FslGu6fDztKX9JYTBMxUXxdziUAru8w9RO/++KZbc6wTPAbkCpVYNhjtgcwXkWSEDocWJJyBQlyULH7YoC9b6JrNliXiFqKek7EcCQ/bzm55G,iv:gjDabKWR/Pw89IjbRNnL6lHaKtzFRb851jgRGJk5a2c=,tag:h6/2sPa+h4JX39NEIzOpRQ==,type:str]
    SESSION_KEY: ENC[AES256_GCM,data:MvGzqQcxjttOr8qCalJ1MRkZN2RIxa8qE0Cwyed9TPQVicpGC4+/HePrAr4=,iv:9hMkwts39gcsocZgEpVELXZUOLB+sCtfOnvGVuO111A=,tag:lqTK7I9F3dBLAF6hFFDCWg==,type:str]
    RESEND_API_KEY: ENC[AES256_GCM,data:DVRZdM1RnHNLfDDPcymnfmswjVfSQwmbCA3QCmLBLxU4x8Fc,iv:1o+XNxD3tfCg2fU1iI87tlaZlU9/2vlHWClfZzrM3MQ=,tag:Eidh9bcNZJLnF+YyB3nt8A==,type:str]
sops:
    age:
        - recipient: age1p0vkumkk7q8ru6skfdqttdjeradz78s7fua8mvv54apt935yzsyqyleqjr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUmhGZVYxcE9XYVFXMWtt
            ejdlb2hBSnMxRjVwRldJL0xYaW00WDZjcmxJCllZWmFiUmxWUWJhZVVTcHJEcFVS
            OFlOMS9WMW5IeXVBVFBaQ1drSFJEM1EKLS0tIE96ZDhtTTJ3eWUwR0lqV3Y5cTFQ
            WHdEQmdCYy9ZYWFJOW1oeFo5RkpTcVUKeNF77JPqFMoLBLy8xTyn2SfDY0QHcghm
            0ipZT0IO3wenhSDayADjRojWswpyUi9xxcuar0f+PfD7kLqpMuFzsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-27T04:32:45Z"
    mac: ENC[AES256_GCM,data:7BjHDsqvrhbbTXhpzpVubudlg+kB0Id1j5Bxjl7J6sk1a5EtrRtNEhqglHVAIVmz6AGnwsUf1vZIuuLpK3Yc0uOzP6n/YOJXgmA96W85NEdAnvyfCGcTJCH4l+Oi8M0I40VFaokJH2zl8Nyfe53+kfvY7akw0Bv9QKfsh0CTnOA=,iv:PAsO/sK0tQ+507jgOSTSe9bCrAqA0ioyxgPtBz7L2Vw=,tag:eO14ws0f+KEVoTHAAcT4Eg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
