apiVersion: v1
kind: Secret
metadata:
    name: jotty-secret
    namespace: jotty
type: Opaque
stringData:
    AUTH_MODE: ENC[AES256_GCM,data:9t7AjZA=,iv:Mkpgqz8gs8a2drM7mCWfnJQ/6r06FvkLHq/z2Ofwf8U=,tag:gtHe3uufboCG7EItqbwC/A==,type:str]
    OIDC_ISSUER: ENC[AES256_GCM,data:hL244157FTtR016A1aa1BMhAHlGyM5AnmHi4,iv:Uk3fVJIN+aGJidpyh5EKSiJveWY/VdoyA6AzyAK5m3Q=,tag:nnE6EdLb4BkvIT+jGpW6IA==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:/EMmtq6CFBWGUl65BzgZYULCVekP,iv:3ZvzZHELqKlPwtc4BHdYhuOXJ0pLvvfoDvIziFhAmCo=,tag:cIvBV+qSO/PHVYMsQkSwVw==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:Pkj/ZFihi6f6dFCD7hWdDD8ujS6+SXI2tA==,iv:Xh5kWtkSAA0PMhYi67RcCdeLTfNGhIxXc33Y7YITppw=,tag:7mgn6Cqfczf3fzjTtgGFrA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrNStqd1JQRE9PNVljNi9y
            MHR5eDNKb0pxTktrNkZucE45UFA4Sko1ZDFVCnlJVDlCKzVxSXVUODlIbVpmcUhm
            c3ROY0RCQmhxN2xDb09DTW9SWkhITmsKLS0tIHE3RHRsOVVZSlFUakJoemNvTTZQ
            bm9ObDRQMXN2QUppQkplcnAzYjU2bjQKcmwsxCLEhkjw2HTaZ9KJNtJBTLSImOem
            9Iz5qWGIlIcepIZc77fwkt+NvPavyw5qpor3XdCyyjmWvhxUzmpzaQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1p0vkumkk7q8ru6skfdqttdjeradz78s7fua8mvv54apt935yzsyqyleqjr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T00:59:59Z"
    mac: ENC[AES256_GCM,data:L9gR8eiSTRshQg7OhkXqmirSRgoQnXe8Uofgddyj0x+aRgnEAY46LOyfhvvV7ZPZYCFpK4ImxqxqOHQhR95HAOn2UDpujnrQ1tdLnu4OQUXpusL7AKPfnfSJWsti6vKT/6qWWVpftJ0jxFT0w7AlXF5XGDT8b5rFEzB0Ytr63xg=,iv:sAyfTGmvYY/jaUKFR4CA6e0LM4f60pDr8bU3nEwA3hg=,tag:nmTpFaan2cvLtXEwyAXiqA==,type:str]
    version: 3.13.3
