apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik-system
spec:
  interval: 1h
  chart:
    spec:
      chart: traefik
      version: "26.1.0"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  install:
    createNamespace: true
    disableWait: true
  upgrade:
    disableWait: true
  targetNamespace: traefik-system
  values:
    ingressClass:
      enabled: true
      isDefaultClass: true
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
    service:
      enabled: true
      type: LoadBalancer
