apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: intel-device-plugins-gpu
  namespace: intel-device-plugins
spec:
  interval: 1h
  chart:
    spec:
      chart: intel-device-plugins-gpu
      version: "0.34.1" # Pinned version or latest stable
      sourceRef:
        kind: HelmRepository
        name: intel
        namespace: flux-system
  install:
    createNamespace: true
  targetNamespace: intel-device-plugins
  values:
    nodeSelector:
      hardware-type: intel-gpu
