apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: channels-dvr-config
  namespace: channels-dvr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: channels-dvr-recordings
  namespace: channels-dvr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 100Gi
