apiVersion: v1
kind: Secret
metadata:
    name: runway-secret
    namespace: runway
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:Q/GGuwbY,iv:LwehhIO3MAZKqjXG39u28nf9WviRZfj8I/nguO3DgTA=,tag:Gwl86hunM7rAjdfF5sJZ0Q==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:2Abiss47XTN49UgixvUBZtZBakrrl0bmH4iFftuDdvE=,iv:pdyMjDL88PaAhec7zp0nF1Xf4QIuPwn1vF28yKFHccs=,tag:OLrnhRrT/bCfZ8t+vyM9FA==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:me004d5Y,iv:ps01FZq/QMtxhQECdz5cHJ+StKCDjcdyCj8wrPQ0rEc=,tag:OcWyTLo+SVOoESnGPnJ+ew==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:t9u1I6S6OCZ01QtX4vsE8tkj9nd4jqtJxf+C0+ceGr59JPjdfDKV19DlyoVX81jNh7GdQHbnJqg3dZkWMvz6yK2v7vljkvVdpg==,iv:TmAM26RxjOnUkz1XtjEGTJeclE3vnUoHu40Zd8aDCZo=,tag:1YIj2eLhK00pla6Yat7NDA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaWUFRU2M2Q0p5OVByTmFJ
            ZTYyeDZoUTJRUDR5VEtobHlqQkxibk9DNzNFCmhPQ3NQRmJKeUtheHM5THcvU1ha
            enpMVndBWmFoTFU3ZDZMUkRMQmRNME0KLS0tIE5hcTNibU1WZ2JrSlZxREJIMWR6
            Q2IyZFhGbDJBa0E2WUNKa29ieXFMdGsKaRMdifGWXc62UZ6iTUEqUbrCiww6RN7k
            FycBDF+71ieIR95hUYWyz+cOCEkaN5fvS63fvN3MXPrYEMjkRP0Nfw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1p0vkumkk7q8ru6skfdqttdjeradz78s7fua8mvv54apt935yzsyqyleqjr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T22:02:05Z"
    mac: ENC[AES256_GCM,data:DjOaN11usEpmSkFmkzJtqc7Jr1s+eQN/88sdcDUanpfRZWcEckUOmX8gQhP7FeG0AMbLXGmgXXJa6YAuoaPNsdd+GVcFMPG6groqqdJ35de9x7UVnkeNY1nhtCmkGV9iUZJRf5st+HL93g299TrT9nxZXj/uKYMGUik6PS1kL4A=,iv:w8YINdAlU0LkARUM2RSczs0NwEqGVofIJYlX2dFicK4=,tag:hrsw0Kl70loBXBmeKOd7XQ==,type:str]
    version: 3.13.3
