apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pi-hole-etc-pihole
  namespace: pi-hole
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pi-hole-etc-dnsmasq
  namespace: pi-hole
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
